/**
 * A source file generated by TWI1 I2C host driver.
 *
 * @file twi1.c
 *
 * @ingroup i2c_host_interrupt
 *
 * @brief This file contains the API implementation for TWI1 driver.
 *
 * @version TWI1 Driver Version 2.1.5
 * 
 * @version TWI1 Package Version 8.2.1
 */

/*
© [2026] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip 
    software and any derivatives exclusively with Microchip products. 
    You are responsible for complying with 3rd party license terms  
    applicable to your use of 3rd party software (including open source  
    software) that may accompany Microchip software. SOFTWARE IS ?AS IS.? 
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS 
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,  
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT 
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF 
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE 
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP?S 
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT 
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR 
    THIS SOFTWARE.
*/

/**
 * @misradeviation {@advisory,2.5} False positive - A few macros in this file 
 * are used as arguments but are not getting recognized by the tool.
 * This rule ID has been disabled at the project level due to numerous 
 * instances across various files.
 * Consequently, in the application project, this rule ID must be disabled
 * in the MPLAB-X IDE by navigating to Tools>Options>Embedded>MISRA Check.
 */

#include "../twi1.h"
#include <stdbool.h>
#include <stdlib.h>
#include "../../system/utils/compiler.h"

static void TWI1_Close(void);
static void TWI1_ReadStart(void);
static void TWI1_WriteStart(void);
static void TWI1_EventHandler(void);
static void TWI1_ErrorEventHandler(void);

static i2c_event_states_t I2C_EVENT_IDLE(void);
static i2c_event_states_t I2C_EVENT_SEND_RD_ADDR(void);
static i2c_event_states_t I2C_EVENT_SEND_WR_ADDR(void);
static i2c_event_states_t I2C_EVENT_TX(void);
static i2c_event_states_t I2C_EVENT_RX(void);
static i2c_event_states_t I2C_EVENT_NACK(void);
static i2c_event_states_t I2C_EVENT_ERROR(void);
static i2c_event_states_t I2C_EVENT_STOP(void);
static i2c_event_states_t I2C_EVENT_RESET(void);

static inline void TWI1_CommandUpdate(TWI_MCMD_t cmd);
static void (*TWI1_Callback)(void);
static volatile i2c_event_status_t twi1_Status = {0};

const i2c_host_interface_t I2C1_Host = 
{
    .Initialize = TWI1_Initialize,
    .Deinitialize = TWI1_Deinitialize,
    .Write = TWI1_Write,
    .Read = TWI1_Read,
    .WriteRead = TWI1_WriteRead,
    .TransferSetup = NULL,
    .ErrorGet = TWI1_ErrorGet,
    .IsBusy = TWI1_IsBusy,
    .CallbackRegister = TWI1_CallbackRegister,
    .Tasks = NULL
};

typedef i2c_event_states_t (*twi1eventHandler)(void);
static const twi1eventHandler twi1_eventTable[] = 
{
    I2C_EVENT_IDLE,
    I2C_EVENT_SEND_RD_ADDR,
    I2C_EVENT_SEND_WR_ADDR,
    I2C_EVENT_TX,
    I2C_EVENT_RX,
    I2C_EVENT_NACK,
    I2C_EVENT_ERROR,
    I2C_EVENT_STOP,
    I2C_EVENT_RESET
};

void TWI1_Initialize(void)
{
    
    // Disable the peripheral
    TWI1.MCTRLA &= ~(1 << TWI_ENABLE_bp);

    // FMPEN OFF; INPUTLVL I2C; SDAHOLD OFF; SDASETUP 4CYC; 
    TWI1.CTRLA = (uint8_t)0x0;

    // Debug Run
    TWI1.DBGCTRL = (uint8_t)0x0;

    // Host Baud Rate Control
    TWI1.MBAUD = (uint8_t)TWI1_BAUD(104166, 0.1);

    // Host Address
    TWI1.MADDR = (uint8_t)0x0;

    // Host Data
    TWI1.MDATA = (uint8_t)0x0;
   
    // ARBLOST disabled; BUSERR disabled; BUSSTATE UNKNOWN; CLKHOLD disabled; RIF disabled; WIF disabled; 
    TWI1.MSTATUS = (uint8_t)0x0;

    // ACKACT ACK; FLUSH disabled; MCMD NOACT; 
    TWI1.MCTRLB = (uint8_t)0x0;
  
    // ENABLE enabled; QCEN disabled; RIEN enabled; SMEN disabled; TIMEOUT DISABLED; WIEN enabled; 
    TWI1.MCTRLA = (uint8_t)0xC1;

    // Force bus to go in idle state
    TWI1.MSTATUS = TWI_BUSSTATE_IDLE_gc; 

    TWI1_Callback = NULL;
}

void TWI1_Deinitialize(void)
{
    // FMPEN OFF; INPUTLVL I2C; SDAHOLD OFF; SDASETUP 4CYC; 
    TWI1.CTRLA = (uint8_t)0x00;
    
    // Debug Run
    TWI1.DBGCTRL = (uint8_t)0x00;
    
    // Host Baud Rate Control
    TWI1.MBAUD = (uint8_t)TWI1_BAUD(104166, 0.1);
    
    // ENABLE enabled; QCEN disabled; RIEN enabled; SMEN disabled; TIMEOUT DISABLED; WIEN enabled; 
    TWI1.MCTRLA = (uint8_t)0x00;
    
    // ARBLOST disabled; BUSERR disabled; BUSSTATE UNKNOWN; CLKHOLD disabled; RIF disabled; WIF disabled; 
    TWI1.MSTATUS = (uint8_t)0x00;

    // Host Address
    TWI1.MADDR = (uint8_t)0x00;
    
    // ACKACT ACK; FLUSH disabled; MCMD NOACT; 
    TWI1.MCTRLB = (uint8_t)0x00;
    
    // Host Data
    TWI1.MDATA = (uint8_t)0x00;

    TWI1.MCTRLA &= ~(1 << TWI_ENABLE_bp);
    // Force bus to go in idle state
    TWI1.MSTATUS = TWI_BUSSTATE_IDLE_gc;
    
}

bool TWI1_Write(uint16_t address, uint8_t *data, size_t dataLength)
{
    bool retStatus = false;
    
    if (!TWI1_IsBusy())
    {
        twi1_Status.busy = true;
        twi1_Status.address = address;
        twi1_Status.switchToRead = false;
        twi1_Status.writePtr = data;
        twi1_Status.writeLength = dataLength;
        twi1_Status.readPtr = NULL;
        twi1_Status.readLength = (uint16_t)0;
        twi1_Status.errorState = I2C_ERROR_NONE;
        TWI1_WriteStart();
        retStatus = true;
    }
    
    return retStatus;
}

bool TWI1_Read(uint16_t address, uint8_t *data, size_t dataLength)
{
    bool retStatus = false;
    
    if (!TWI1_IsBusy())
    {
        twi1_Status.busy = true;
        twi1_Status.address = address;
        twi1_Status.switchToRead = false;
        twi1_Status.readPtr = data;
        twi1_Status.readLength = dataLength;
        twi1_Status.writePtr = NULL;
        twi1_Status.writeLength = (uint16_t)0;
        twi1_Status.errorState = I2C_ERROR_NONE;
        TWI1_ReadStart();
        retStatus = true;
    }
    
    return retStatus;
}

bool TWI1_WriteRead(uint16_t address, uint8_t *writeData, size_t writeLength, uint8_t *readData, size_t readLength)
{
    bool retStatus = false;
    
    if (!TWI1_IsBusy())
    {
        twi1_Status.busy = true;
        twi1_Status.address = address;
        twi1_Status.switchToRead = true;
        twi1_Status.writePtr = writeData;
        twi1_Status.writeLength = writeLength;
        twi1_Status.readPtr = readData;
        twi1_Status.readLength = readLength;
        twi1_Status.errorState = I2C_ERROR_NONE;
        TWI1_WriteStart();
        retStatus = true;
    }
    
    return retStatus;
}

i2c_host_error_t TWI1_ErrorGet(void)
{
    i2c_host_error_t retErrorState = twi1_Status.errorState;
    twi1_Status.errorState = I2C_ERROR_NONE;
    
    return retErrorState;
}

bool TWI1_IsBusy(void)
{
    return (twi1_Status.busy || ((TWI1.MSTATUS & TWI_BUSSTATE_gm) != TWI_BUSSTATE_IDLE_gc));
}

void TWI1_CallbackRegister(void (*callbackHandler)(void))
{
    if (callbackHandler != NULL)
    {
        TWI1_Callback = callbackHandler;
    }
}

static void TWI1_Close(void)
{
    twi1_Status.busy = false;
    twi1_Status.address = (uint16_t)0xFF;
    twi1_Status.writePtr = NULL;
    twi1_Status.readPtr = NULL;
    twi1_Status.state = I2C_STATE_IDLE;
    // Clear interrupt status
    TWI1.MSTATUS = (uint8_t)(TWI_RIF_bm | TWI_WIF_bm);
    TWI1.MSTATUS = TWI_BUSSTATE_IDLE_gc;
}

static void TWI1_ReadStart(void)
{
    twi1_Status.state = I2C_EVENT_SEND_RD_ADDR();
}

static void TWI1_WriteStart(void)
{
    twi1_Status.state = I2C_EVENT_SEND_WR_ADDR();
}

static void TWI1_EventHandler(void)
{
    twi1_Status.state = twi1_eventTable[twi1_Status.state]();
}

static void TWI1_ErrorEventHandler(void)
{
    // Check the bus error
    if ((TWI1.MSTATUS & TWI_BUSERR_bm) || (TWI1.MSTATUS & TWI_ARBLOST_bm))
    {
        twi1_Status.state = I2C_STATE_ERROR;
        twi1_Status.errorState = I2C_ERROR_BUS_COLLISION;
        
        // Clear the error flags
        TWI1.MSTATUS = (uint8_t)(TWI_BUSERR_bm | TWI_ARBLOST_bm);
    }
    // Check if address NAK
    else if ((TWI1.MADDR) && (TWI1.MSTATUS & TWI_RXACK_bm))
    {
        twi1_Status.state = I2C_STATE_NACK;
        twi1_Status.errorState = I2C_ERROR_ADDR_NACK;
    }
    // Check if data NAK
    else if ((TWI1.MDATA) && (TWI1.MSTATUS & TWI_RXACK_bm))
    {
        twi1_Status.state = I2C_STATE_NACK;
        twi1_Status.errorState = I2C_ERROR_DATA_NACK;
    }
    else
    {
        // No action required
    }
    
    twi1_Status.state = twi1_eventTable[twi1_Status.state]();
    
    if(twi1_Status.errorState != I2C_ERROR_NONE)
    {
        if (TWI1_Callback != NULL)
        {
            TWI1_Callback();
        }
    }
}

/* I2C Event interfaces */
static i2c_event_states_t I2C_EVENT_IDLE(void)
{
    twi1_Status.busy = false;
    // Force bus to go in idle state
    TWI1.MSTATUS = TWI_BUSSTATE_IDLE_gc;
    
    return I2C_STATE_RESET;
}

static i2c_event_states_t I2C_EVENT_SEND_RD_ADDR(void)
{
    TWI1.MADDR = (uint8_t) ((twi1_Status.address << 1) | 1U);
    return I2C_STATE_RX;
}

static i2c_event_states_t I2C_EVENT_SEND_WR_ADDR(void)
{
    TWI1.MADDR = (uint8_t) (twi1_Status.address << 1);
    
    return I2C_STATE_TX;
}

static i2c_event_states_t I2C_EVENT_TX(void)
{
    i2c_event_states_t retEventState = I2C_STATE_TX;

        if (0U != twi1_Status.writeLength)
        {
            twi1_Status.writeLength--;
            TWI1.MDATA = *twi1_Status.writePtr;
            twi1_Status.writePtr++;
            retEventState = I2C_STATE_TX;
        }
        else
        {
            if (twi1_Status.switchToRead)
            {
                twi1_Status.switchToRead = false;
                retEventState = I2C_STATE_SEND_RD_ADDR;
            }
            else
            {
                retEventState = I2C_EVENT_STOP();
            }
        }

    return retEventState;
}

static i2c_event_states_t I2C_EVENT_RX(void)
{
    i2c_event_states_t retEventState = I2C_STATE_RX;

    if (twi1_Status.readLength == 1U)
    {
        // Next byte will be last to be received, setup NACK
        TWI1.MCTRLB |= TWI_ACKACT_bm;
    }
    else
    {
        // More bytes to receive, setup ACK
        TWI1.MCTRLB &= ~TWI_ACKACT_bm;
    }

    if (0U != --twi1_Status.readLength)
    {
        *twi1_Status.readPtr = TWI1.MDATA;
        twi1_Status.readPtr++;
        // Execute Acknowledge Action followed by a byte read operation
        TWI1_CommandUpdate(TWI_MCMD_RECVTRANS_gc);
        retEventState = I2C_STATE_RX;
    }
    else
    {
        *twi1_Status.readPtr = TWI1.MDATA;
        twi1_Status.readPtr++;
        // Next byte will be last to be received, setup NACK
        TWI1.MCTRLB |= TWI_ACKACT_bm;
        retEventState = I2C_EVENT_STOP();
    }

    return retEventState;
}

static i2c_event_states_t I2C_EVENT_NACK(void)
{
    i2c_event_states_t retEventState = I2C_STATE_NACK;
    retEventState = I2C_EVENT_STOP();
    
    return retEventState;
}

static i2c_event_states_t I2C_EVENT_ERROR(void)
{
    // Clear bus collision status flag
    i2c_event_states_t retEventState = I2C_STATE_ERROR;
    // Clear interrupt status
    TWI1.MSTATUS = (uint8_t)(TWI_RIF_bm | TWI_WIF_bm);
    retEventState = I2C_EVENT_RESET();
    
    return retEventState;
}

static i2c_event_states_t I2C_EVENT_STOP(void)
{
    // Send stop
    TWI1_CommandUpdate(TWI_MCMD_STOP_gc);
    TWI1_Close();
    
    return I2C_STATE_IDLE;
}

static i2c_event_states_t I2C_EVENT_RESET(void)
{
    // Reset the bus
    TWI1.MCTRLA &= ~(1 << TWI_ENABLE_bp);
    TWI1.MCTRLA |= 1 << TWI_ENABLE_bp;

    twi1_Status.busy = false;
    
    return I2C_STATE_IDLE;
}

static inline void TWI1_CommandUpdate(TWI_MCMD_t cmd)
{
    TWI1.MCTRLB = ((TWI1.MCTRLB & (uint8_t)(~TWI_MCMD_gm)) | (uint8_t)cmd);  
}

/** 
 * @misradeviation{@advisory,2.7} False positive - ISR is a pre-processor macro, 
 * defined in interrupt., and is wrongly treated as a function by the CPP Checker.
 * 
 * @misradeviation{@required,8.2,@required,8.4} False positive - ISR is a pre-processor macro 
 * defined in interrupt.h. The CPP Checker wrongly treats ISR as a function and expects 
 * a declaration to be available.
 *
 * @misradeviation{@required,5.5} False positive - ISR is a pre-processor macro, 
 * defined in interrupt.h file provided by XC8 compiler and is redefined in utils/interrupt_avr.h 
 * this file is out of scope for the MISRA check here but is considered by CPP Checker.
 */
/* cppcheck-suppress misra-c2012-2.7 */
/* cppcheck-suppress misra-c2012-8.2 */
/* cppcheck-suppress misra-c2012-8.4 */
/**
 * @ingroup i2c_host
 * @brief Common Interrupt Service Routine (ISR) for all TWI1 interrupts. 
 * Initialize TWI1 with TWI1_Initialize() before calling this API. \n
 * This API calls the TWI1_ErrorEventHandler() if an error flag is set, otherwise it calls
 * TWI1_EventHandler() for other TWI transmit and receive events.
 * @param None.
 * @return None. \n
 */
ISR(TWI1_TWIM_vect)
{/* cppcheck-suppress misra-c2012-5.5 */
   if ((uint8_t)0U != (TWI1.MSTATUS & (uint8_t)(TWI_RXACK_bm | TWI_BUSERR_bm | TWI_ARBLOST_bm)))
   {
    TWI1_ErrorEventHandler();
   }
   else if ((uint8_t)0U != (TWI1.MSTATUS & (uint8_t)(TWI_RIF_bm | TWI_WIF_bm | TWI_CLKHOLD_bm)))
   {
    TWI1_EventHandler();
   }
   else
   {
       // No action required
   }
}

